[project]
name = "portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "firecrawl-py>=1.0.0",
    "google-genai>=2.16.0",
    "langchain-core>=0.3.0",
    "openai>=2.53.0",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.52.1",
]

